# Generated by Django 3.1.6 on 2021-02-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210222_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reviews',
            field=models.TextField(default=True, max_length=100, null=True),
        ),
    ]
