# Generated by Django 3.1.6 on 2021-02-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20210223_0928'),
        ('genres', '0004_genre_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='test',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='movies',
        ),
        migrations.AddField(
            model_name='genre',
            name='movies',
            field=models.ManyToManyField(related_name='movies', to='movies.Movie'),
        ),
    ]
