# Generated by Django 3.1.6 on 2021-02-23 09:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(default=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
