# Generated by Django 3.2.3 on 2021-06-02 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='room',
            new_name='movie',
        ),
    ]
