# Generated by Django 3.2.3 on 2021-06-03 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_alter_photo_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AbstarctItem',
        ),
    ]
