# Generated by Django 3.2.3 on 2021-06-03 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_delete_abstarctitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='file',
            new_name='files',
        ),
    ]
